/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pfatool.tmpgenerated;
@org.apache.avro.specific.AvroGenerated
public enum ColumnNames implements org.apache.avro.generic.GenericEnumSymbol<ColumnNames> {
  x0, x1, x2, x3  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ColumnNames\",\"namespace\":\"pfatool.tmpgenerated\",\"symbols\":[\"x0\",\"x1\",\"x2\",\"x3\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
