name: Java unit tests

# manually triggered
on: workflow_dispatch

jobs:
  run_unit_tests:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: run unit tests
        timeout-minutes: 3
        run: |
          ./gradlew --rerun-tasks test
